### ISSUE TITLE
detect available backends properly

### ISSUE THREAD

**Issue by blshkv** [skelsec/unicrypto#2]
Hello, 

I know that the software requires pycryptodomex, however it seems old and was replaced by pycryptodome.

Could you adapt the code please? Currently, i'm getting the following error:

```
>>> from aardwolf.commons.url import RDPConnectionURL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/aardwolf/commons/url.py", line 6, in <module>
    from aardwolf.commons.authbuilder import AuthenticatorBuilder
  File "/usr/lib/python3.10/site-packages/aardwolf/commons/authbuilder.py", line 9, in <module>
    from aardwolf.authentication.ntlm.native import NTLMAUTHHandler, NTLMHandlerSettings
  File "/usr/lib/python3.10/site-packages/aardwolf/authentication/ntlm/native.py", line 17, in <module>
    from aardwolf.authentication.ntlm.creds_calc import *
  File "/usr/lib/python3.10/site-packages/aardwolf/authentication/ntlm/creds_calc.py", line 3, in <module>
    from unicrypto.symmetric import DES
  File "/usr/lib/python3.10/site-packages/unicrypto/symmetric.py", line 82, in <module>
    DES = get_preferred_cipher('DES')
  File "/usr/lib/python3.10/site-packages/unicrypto/__init__.py", line 74, in get_preferred_cipher
    return get_cipher_by_name(ciphername, selected_module)
  File "/usr/lib/python3.10/site-packages/unicrypto/__init__.py", line 52, in get_cipher_by_name
    return import_from(moduleName , ciphername)
  File "/usr/lib/python3.10/site-packages/unicrypto/__init__.py", line 15, in import_from
    module = __import__(module, fromlist=[name])
  File "/usr/lib/python3.10/site-packages/unicrypto/backends/pycryptodome/DES.py", line 2, in <module>
    from Cryptodome.Cipher import DES as _pyCryptodomeDES
ModuleNotFoundError: No module named 'Cryptodome'

```

**Comment by blshkv** [comment]
```
    try:  # The crypto package depends on the library installed (see Wiki)
        from Crypto.Cipher import AES
        from Crypto.Util import Padding
    except ImportError:
        from Cryptodome.Cipher import AES
        from Cryptodome.Util import Padding
```

**Comment by blshkv** [comment]
hm.. interesting. I do have the following two libraries installed, however the error is still there:
dev-python/pycryptodome
dev-python/cryptography

FYI, pycryptodome-3.14.1 installed as "Crypto" module

**Comment by byehack** [comment]
I'm sure it solved in https://github.com/skelsec/unicrypto/pull/1
it seems your using version 0.0.5
please update to latest version that is 0.0.9 now.

**Comment by blshkv** [comment]
ok, great. Thanks
